# Generated by Django 5.0.3 on 2024-04-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Telegram bot', max_length=100, verbose_name='Fullname')),
                ('photo', models.CharField(default='https://www.base.uz/image.jpg', max_length=200, verbose_name='Rasm')),
                ('description', models.TextField(default='about this servis', max_length=3000, verbose_name='Xizmat haqida')),
                ('basic_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Basic package price')),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Standard package price')),
                ('premium_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Premium package price')),
                ('package', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20, verbose_name='Package')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fullname')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Username')),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram_id')),
            ],
        ),
    ]
