# Generated by Django 5.0.3 on 2024-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_services_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='Xizmat haqida'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Fullname'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.CharField(max_length=200, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram_id'),
        ),
    ]
