# Generated by Django 5.0.3 on 2024-04-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_services_description_alter_services_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='basic_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Basic package price'),
        ),
        migrations.AlterField(
            model_name='services',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Premium package price'),
        ),
        migrations.AlterField(
            model_name='services',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Standard package price'),
        ),
    ]
