# Generated by Django 5.0.6 on 2024-06-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arizalar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Ariza Raqami')),
                ('name', models.CharField(max_length=100, verbose_name='Ism Familiya')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('user_id', models.BigIntegerField(verbose_name='Telegram_id')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqami')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Xizmat nomi')),
                ('photo', models.CharField(max_length=300, verbose_name='Rasm')),
                ('description', models.TextField(max_length=3000, verbose_name='Xizmat haqida')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField(default=3, editable=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Premium', editable=False, max_length=255, verbose_name='Full Name')),
                ('description', models.TextField(verbose_name='Xizmat haqida - Premium')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Premium package price')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_service', to='users.service')),
            ],
        ),
        migrations.CreateModel(
            name='BasicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField(default=1, editable=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Basic', editable=False, max_length=255, verbose_name='Full Name')),
                ('description', models.TextField(verbose_name='Xizmat haqida - Basic')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Basic package price')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_service', to='users.service')),
            ],
        ),
        migrations.CreateModel(
            name='StandardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField(default=2, editable=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Standard', editable=False, max_length=255, verbose_name='Full Name')),
                ('description', models.TextField(verbose_name='Xizmat haqida - Standard')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Standard package price')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_service', to='users.service')),
            ],
        ),
    ]
