# Generated by Django 5.0.6 on 2024-06-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicservice',
            name='iid',
            field=models.IntegerField(default=1, editable=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='premiumservice',
            name='iid',
            field=models.IntegerField(default=3, editable=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='standardservice',
            name='iid',
            field=models.IntegerField(default=2, editable=False, verbose_name='ID'),
        ),
    ]
