# Generated by Django 5.0.6 on 2024-06-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_premiumservice_selected_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumservice',
            name='selected_package',
        ),
        migrations.AddField(
            model_name='arizalar',
            name='selected_package',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, null=True, verbose_name='Tanlangan Paket'),
        ),
    ]
