# Generated by Django 5.0.6 on 2024-06-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_services_basic_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Xizmat haqida - Basic')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Basic package price')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Xizmat haqida - Premium')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Premium package price')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Xizmat nomi')),
                ('photo', models.CharField(max_length=300, verbose_name='Rasm')),
                ('description', models.TextField(max_length=3000, verbose_name='Xizmat haqida')),
            ],
        ),
        migrations.CreateModel(
            name='StandardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Xizmat haqida - Standard')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Standard package price')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_service', to='users.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='premiumservice',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_service', to='users.service'),
        ),
        migrations.AddField(
            model_name='basicservice',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_service', to='users.service'),
        ),
    ]
