# Generated by Django 5.0.6 on 2024-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_premiumservice_selected_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arizalar',
            name='selected_package',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20, null=True, verbose_name='Tanlangan Paket'),
        ),
    ]
