# Generated by Django 5.0.6 on 2024-06-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_arizalar_selected_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegram_id',
            new_name='user_id',
        ),
    ]
