# Generated by Django 5.0.6 on 2024-06-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_telegram_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='telegram_id',
        ),
    ]
