# Generated by Django 5.0.6 on 2024-06-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_user_id_user_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegram_id',
            new_name='user_id',
        ),
    ]
